/**
 * The enclave against the contract: same inputs, same answer, or the private path is a different
 * lender wearing the same name.
 *
 * `handlers.ts` says its arithmetic "mirrors AdvanceManager exactly". That sentence is the whole
 * basis for trusting a decision nobody outside the enclave can see — and until this suite existed,
 * nothing enforced it. The fixture holds the real contract's answer for a matrix of account ages,
 * histories, cycles and period ages, generated by running the deployed underwriting code itself:
 *
 *   npx hardhat run scripts/ledgerline/gen-underwriting-fixture.ts
 *
 * Regenerate it whenever the underwriting policy changes on either side. A divergence here is not a
 * test failure to be papered over; it means a borrower would be told two different numbers.
 */

import { describe, expect, it } from "vitest";

import { bytesToHex } from "../base/encoding.js";
import { handleComputeLimit } from "../app/handlers.js";
import fixture from "./fixtures/underwriting.json" with { type: "json" };

interface Case {
    name: string;
    input: {
        accountId: string;
        nowTs: number;
        accountCreatedAt: number;
        closedCleanCycles: number;
        periods: { revenueCents: number; periodStart: number; periodEnd: number; refundCents?: number }[];
    };
    onChain: { limitCents: number; factorBps: number; feeBps: number; periodsUsed: number };
}

function enclaveAnswer(input: Case["input"]) {
    const hex = bytesToHex(Buffer.from(JSON.stringify(input), "utf-8"));
    const [data, status, err] = handleComputeLimit(hex);
    if (status !== 1 || !data) throw new Error(`enclave refused: ${err}`);
    return JSON.parse(Buffer.from(data.slice(2), "hex").toString("utf-8"));
}

describe("Differential: the enclave reproduces the contract, case by case", () => {
    const cases = (fixture as { cases: Case[] }).cases;

    it("the fixture covers the policy surface it claims to", () => {
        expect(cases.length).toBeGreaterThanOrEqual(12);
        // Provisional revenue is where a naive mirror diverges, so the matrix must contain some.
        const provisional = cases.filter((c) =>
            c.input.periods.some((p) => c.input.nowTs - p.periodEnd < 120 * 24 * 60 * 60)
        );
        expect(provisional.length).toBeGreaterThanOrEqual(4);
    });

    for (const c of cases) {
        it(`${c.name}`, () => {
            const got = enclaveAnswer(c.input);
            expect(got.limitCents, "limit").toBe(c.onChain.limitCents);
            expect(got.factorBps, "factor").toBe(c.onChain.factorBps);
            expect(got.feeBps, "fee").toBe(c.onChain.feeBps);
            expect(got.periodsUsed, "periods used").toBe(c.onChain.periodsUsed);
        });
    }
});
